language: java

jdk:
  - oraclejdk7
  - openjdk7
  #- openjdk6

before_install:
  - sudo usermod -G shippable www-data
  - sudo chmod 0777 $SHIPPABLE_REPO_DIR
archive: true
cache: true
build_image: shippable/minv2:beta
